### ISSUE TITLE
Высота отзыва

### ISSUE THREAD

**Issue by foxhable** [aaccent/smart_layout#128]
Из-за разной высоты текста в элементах дата становится не на линии с кнопками. Для исправления нужно применить стили:

```scss
.reviews__item {
  height: auto;
}

.reviews__item-content {
  height: 100%;
  display: flex;
  flex-direction: column;
}

.reviews__item-date {
  margin-top: auto;
}
```

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/smart_layout/assets/36298346/311c30ea-6b11-43f3-b728-94b99028aaa2)
</details>
