### ISSUE TITLE
Высота элементов в решениях бизнеса

### ISSUE THREAD

**Issue by foxhable** [aaccent/smart_layout#77]
Если добавить текста в заголовок, то высота элементов становится неравной

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/smart_layout/assets/36298346/f3162021-e06f-4b2f-b3ab-86aec002997f)
</details> 

Нужно применить стили для исправления:

```scss
.solutions {
  &__item {
    height: auto;

    &-title {
      height: 100%;
    }
  }
}
```
